# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

addons:
  apt:
    packages:
      - default-jdk
      - graphviz
      - ghostscript

r_packages:
  - covr
  - lintr

####

after_success:
  - Rscript -e 'covr::codecov()'
#  - Rscript -e 'lintr::lint_package()'
